<a href="https://colab.research.google.com/github/riabhatt-hr/AI_Resume_Parsing_Screening_Lab/blob/main/Chitkara_MBA_AI_Resume_Parsing_Screening_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI-Based Resume Screening and Parsing Lab

## Lab Objective
The objective of this lab is to help learners understand how AI-assisted resume screening works by:

1. Creating a synthetic dataset of 20 candidate resumes.
2. Simulating resume parsing using text extraction logic.
3. Extracting structured information such as:
   - skills
   - experience
   - education
4. Comparing candidate resumes with a job description.
5. Performing ATS-style keyword matching.
6. Ranking candidates based on relevance.
7. Identifying best-fit candidates for HR review.

## Learning Outcome
By the end of this lab, students will be able to:
- Understand the concept of resume parsing.
- Convert unstructured resume text into structured candidate information.
- Perform keyword-based filtering similar to ATS systems.
- Compare candidates based on extracted features.
- Understand that AI supports screening, but HR makes the final decision.

In [65]:
# This cell imports the libraries required in this lab.
# pandas is used for data handling.
# re is used for pattern matching and simple text extraction.
# sklearn is used for TF-IDF and cosine similarity.

import pandas as pd
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Display settings to make output easier to read.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

## Step 1: Create Synthetic Resume Dataset
In this step, we create 20 sample resumes.
Each resume is written as unstructured text, just like a real resume document.
This helps us simulate how AI parses resume content.

In [66]:
# This cell creates a synthetic dataset of 20 resumes.
# Each resume is stored as text in one column.
# This simulates real-world unstructured resume data.

resume_data = [
    {"candidate_id": 1, "resume_text": "Aarav has skills in Python, SQL, Excel, and Machine Learning. He has 3 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 2, "resume_text": "Diya has skills in Recruitment, Onboarding, Communication, and Excel. She has 4 years of experience. Education: MBA HR. Certifications: 1."},
    {"candidate_id": 3, "resume_text": "Kabir has skills in Python, SQL, Tableau, Data Analysis, and Pandas. He has 2 years of experience. Education: B.Sc. Certifications: 3."},
    {"candidate_id": 4, "resume_text": "Ishita has skills in Java, SQL, Spring, Teamwork, and Communication. She has 5 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 5, "resume_text": "Vivaan has skills in Python, SQL, Deep Learning, NLP, and BERT. He has 6 years of experience. Education: M.Tech. Certifications: 4."},
    {"candidate_id": 6, "resume_text": "Anaya has skills in Recruitment, Sourcing, Interview Screening, and Communication. She has 3 years of experience. Education: MBA HR. Certifications: 2."},
    {"candidate_id": 7, "resume_text": "Reyansh has skills in Python, SQL, Power BI, Excel, and Statistics. He has 4 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 8, "resume_text": "Myra has skills in Machine Learning, Python, Tableau, and Data Visualization. She has 2 years of experience. Education: M.Sc. Certifications: 3."},
    {"candidate_id": 9, "resume_text": "Arjun has skills in Manual Testing, Selenium, Jira, and Communication. He has 5 years of experience. Education: BCA. Certifications: 1."},
    {"candidate_id": 10, "resume_text": "Siya has skills in Python, SQL, NLP, ML, Communication, and Teamwork. She has 3 years of experience. Education: MCA. Certifications: 3."},
    {"candidate_id": 11, "resume_text": "Krish has skills in Excel, SQL, Dashboarding, Reporting, and Power BI. He has 2 years of experience. Education: B.Com. Certifications: 2."},
    {"candidate_id": 12, "resume_text": "Aadhya has skills in Python, R, Statistics, and Machine Learning. She has 4 years of experience. Education: M.Stat. Certifications: 3."},
    {"candidate_id": 13, "resume_text": "Advik has skills in Project Management, Agile, Scrum, and Communication. He has 6 years of experience. Education: MBA. Certifications: 2."},
    {"candidate_id": 14, "resume_text": "Kiara has skills in Python, SQL, Data Analysis, Recruitment, and HR Analytics. She has 5 years of experience. Education: MBA HR. Certifications: 4."},
    {"candidate_id": 15, "resume_text": "Atharv has skills in C++, Algorithms, Data Structures, and Problem Solving. He has 1 year of experience. Education: B.Tech. Certifications: 1."},
    {"candidate_id": 16, "resume_text": "Navya has skills in Python, SQL, Tableau, Power BI, and Communication. She has 3 years of experience. Education: BBA. Certifications: 2."},
    {"candidate_id": 17, "resume_text": "Rudra has skills in NLP, BERT, Transformers, Python, and Machine Learning. He has 5 years of experience. Education: M.Tech. Certifications: 4."},
    {"candidate_id": 18, "resume_text": "Sara has skills in Recruitment Analytics, Excel, Communication, and HR Operations. She has 4 years of experience. Education: MBA HR. Certifications: 2."},
    {"candidate_id": 19, "resume_text": "Vihaan has skills in Python, SQL, Statistics, Data Cleaning, and Pandas. He has 2 years of experience. Education: B.Sc. Certifications: 2."},
    {"candidate_id": 20, "resume_text": "Meera has skills in Python, Machine Learning, SQL, Communication, and Dashboards. She has 4 years of experience. Education: MCA. Certifications: 3."}
]

df = pd.DataFrame(resume_data)

print("Synthetic resume dataset created successfully.")
df.head()

Synthetic resume dataset created successfully.

   candidate_id                                        resume_text
0             1  Aarav has skills in Python, SQL, Excel, and Ma...
1             2  Diya has skills in Recruitment, Onboarding, Co...
2             3  Kabir has skills in Python, SQL, Tableau, Data...
3             4  Ishita has skills in Java, SQL, Spring, Teamwo...
4             5  Vivaan has skills in Python, SQL, Deep Learnin...

## Step 2: Understand the Resume Dataset
This step helps us inspect:
- number of resumes
- available columns
- overall structure

In [67]:
# This cell checks the dataset shape and column names.

print("Dataset shape:", df.shape)
print("Columns:", list(df.columns))

Dataset shape: (20, 2)
Columns: ['candidate_id', 'resume_text']

## Step 3: View Sample Resume Text
This helps students understand that resumes are initially unstructured text.

In [68]:
# This cell displays a few example resumes.

df.head(3)

   candidate_id                                        resume_text
0             1  Aarav has skills in Python, SQL, Excel, and Ma...
1             2  Diya has skills in Recruitment, Onboarding, Co...
2             3  Kabir has skills in Python, SQL, Tableau, Data...

## Step 4: Parse Skills from Resume Text
Now we simulate resume parsing.
We extract the skills section from the unstructured text.

In [69]:
# This cell extracts skills from each resume using simple text parsing.
# It looks for the text between "skills in" and the next period.

def extract_skills(text):
    match = re.search(r"skills in (.*?)[.] He has|skills in (.*?)[.] She has", text, re.IGNORECASE)
    if match:
        extracted = match.group(1) if match.group(1) else match.group(2)
        return extracted
    return ""

df["skills_extracted"] = df["resume_text"].apply(extract_skills)

df[["candidate_id", "skills_extracted"]].head()

   candidate_id                                   skills_extracted
0             1           Python, SQL, Excel, and Machine Learning
1             2  Recruitment, Onboarding, Communication, and Excel
2             3    Python, SQL, Tableau, Data Analysis, and Pandas
3             4     Java, SQL, Spring, Teamwork, and Communication
4             5          Python, SQL, Deep Learning, NLP, and BERT

## Step 5: Parse Experience from Resume Text
In this step, we extract the years of experience from each resume.

In [70]:
# This cell extracts numeric years of experience from the resume text.
# It searches for patterns such as "3 years of experience".

def extract_experience(text):
    match = re.search(r"(\d+)\s+years of experience", text, re.IGNORECASE)
    if match:
        return int(match.group(1))
    return 0

df["experience_extracted"] = df["resume_text"].apply(extract_experience)

df[["candidate_id", "experience_extracted"]].head()

   candidate_id  experience_extracted
0             1                     3
1             2                     4
2             3                     2
3             4                     5
4             5                     6

## Step 6: Parse Education from Resume Text
Now we extract educational qualification from the resume text.

In [71]:
# This cell extracts education information from the resume text.
# It searches for the value written after "Education:".

def extract_education(text):
    match = re.search(r"Education:\s*([A-Za-z. ]+)", text)
    if match:
        return match.group(1).strip()
    return ""

df["education_extracted"] = df["resume_text"].apply(extract_education)

df[["candidate_id", "education_extracted"]].head()

   candidate_id     education_extracted
0             1  B.Tech. Certifications
1             2  MBA HR. Certifications
2             3    B.Sc. Certifications
3             4  B.Tech. Certifications
4             5  M.Tech. Certifications

## Step 7: Parse Certifications from Resume Text
This step extracts the number of certifications from each resume.

In [72]:
# This cell extracts the certification count from each resume.
# It searches for patterns like "Certifications: 2"

def extract_certifications(text):
    match = re.search(r"Certifications:\s*(\d+)", text, re.IGNORECASE)
    if match:
        return int(match.group(1))
    return 0

df["certifications_extracted"] = df["resume_text"].apply(extract_certifications)

df[["candidate_id", "certifications_extracted"]].head()

   candidate_id  certifications_extracted
0             1                         2
1             2                         1
2             3                         3
3             4                         2
4             5                         4

## Step 8: View Structured Parsed Resume Data
Now we see how unstructured resume text has been transformed into structured candidate information.

In [73]:
# This cell displays the parsed structured data.

parsed_df = df[[
    "candidate_id",
    "resume_text",
    "skills_extracted",
    "experience_extracted",
    "education_extracted",
    "certifications_extracted"
]]

parsed_df.head(10)

   candidate_id                                        resume_text                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted
0             1  Aarav has skills in Python, SQL, Excel, and Ma...           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2
1             2  Diya has skills in Recruitment, Onboarding, Co...  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1
2             3  Kabir has skills in Python, SQL, Tableau, Data...    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3
3             4  Ishita has skills in Java, SQL, Spring, Teamwo...     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2
4             5  Vivaan has skills in Python, SQL, Deep Learnin...          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4
5             6  Anaya has skills in Recruitment, Sourcing, Int...  Recruitment, Sourcing, Interview Screening, an...                     3  MBA HR. Certifications                         2
6             7  Reyansh has skills in Python, SQL, Power BI, E...       Python, SQL, Power BI, Excel, and Statistics                     4  B.Tech. Certifications                         2
7             8  Myra has skills in Machine Learning, Python, T...  Machine Learning, Python, Tableau, and Data Vi...                     2    M.Sc. Certifications                         3
8             9  Arjun has skills in Manual Testing, Selenium, ...  Manual Testing, Selenium, Jira, and Communication                     5     BCA. Certifications                         1
9            10  Siya has skills in Python, SQL, NLP, ML, Commu...  Python, SQL, NLP, ML, Communication, and Teamwork                     3     MCA. Certifications                         3

## Step 9: Define a Job Description
This job description acts as the target profile for matching.

In [74]:
# This cell defines the job description.
# The system will compare candidate resumes with this text.

job_description = "python sql machine learning nlp communication recruitment analytics power bi"

print("Job Description:")
print(job_description)

Job Description:
python sql machine learning nlp communication recruitment analytics power bi

## Step 10: Perform ATS-Style Keyword Matching
An ATS often checks whether candidate resumes contain the required keywords.
We now simulate this process.

In [75]:
# This cell defines required keywords from the job description.
# It then counts how many of these keywords appear in the extracted skills.

required_keywords = ["python", "sql", "machine learning", "nlp", "communication", "recruitment", "analytics", "power bi"]

def keyword_match_count(skill_text):
    skill_text_lower = skill_text.lower()
    count = 0
    for keyword in required_keywords:
        if keyword in skill_text_lower:
            count += 1
    return count

df["keyword_match_count"] = df["skills_extracted"].apply(keyword_match_count)

df[["candidate_id", "skills_extracted", "keyword_match_count"]].head(10)

   candidate_id                                   skills_extracted  keyword_match_count
0             1           Python, SQL, Excel, and Machine Learning                    3
1             2  Recruitment, Onboarding, Communication, and Excel                    2
2             3    Python, SQL, Tableau, Data Analysis, and Pandas                    2
3             4     Java, SQL, Spring, Teamwork, and Communication                    2
4             5          Python, SQL, Deep Learning, NLP, and BERT                    3
5             6  Recruitment, Sourcing, Interview Screening, an...                    2
6             7       Python, SQL, Power BI, Excel, and Statistics                    3
7             8  Machine Learning, Python, Tableau, and Data Vi...                    2
8             9  Manual Testing, Selenium, Jira, and Communication                    1
9            10  Python, SQL, NLP, ML, Communication, and Teamwork                    4

## Step 11: Convert Resume Skills and Job Description into TF-IDF Vectors
Beyond exact keyword matching, AI can compare text similarity.
This helps capture broader relevance.

In [76]:
# This cell converts the job description and extracted skills into TF-IDF vectors.

documents = [job_description] + df["skills_extracted"].tolist()

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (21, 47)

## Step 12: Calculate Cosine Similarity
This step measures how similar each candidate's skills are to the job description.

In [77]:
# This cell calculates cosine similarity between the job description
# and each candidate's extracted skills.

job_vector = tfidf_matrix[0:1]
candidate_vectors = tfidf_matrix[1:]

similarity_scores = cosine_similarity(job_vector, candidate_vectors).flatten()

df["similarity_score"] = similarity_scores

df[["candidate_id", "skills_extracted", "similarity_score"]].head(10)

   candidate_id                                   skills_extracted  similarity_score
0             1           Python, SQL, Excel, and Machine Learning          0.432462
1             2  Recruitment, Onboarding, Communication, and Excel          0.232806
2             3    Python, SQL, Tableau, Data Analysis, and Pandas          0.107773
3             4     Java, SQL, Spring, Teamwork, and Communication          0.122363
4             5          Python, SQL, Deep Learning, NLP, and BERT          0.354681
5             6  Recruitment, Sourcing, Interview Screening, an...          0.179471
6             7       Python, SQL, Power BI, Excel, and Statistics          0.442718
7             8  Machine Learning, Python, Tableau, and Data Vi...          0.261416
8             9  Manual Testing, Selenium, Jira, and Communication          0.059033
9            10  Python, SQL, NLP, ML, Communication, and Teamwork          0.331545

## Step 13: Normalize Experience and Certifications
To combine different candidate attributes fairly, we scale them to the 0–1 range.

In [78]:
# This cell normalizes extracted experience and certification values.

df["experience_score"] = df["experience_extracted"] / df["experience_extracted"].max()
df["certification_score"] = df["certifications_extracted"] / df["certifications_extracted"].max()

df[["candidate_id", "experience_extracted", "experience_score", "certifications_extracted", "certification_score"]].head()

   candidate_id  experience_extracted  experience_score  certifications_extracted  certification_score
0             1                     3          0.500000                         2                 0.50
1             2                     4          0.666667                         1                 0.25
2             3                     2          0.333333                         3                 0.75
3             4                     5          0.833333                         2                 0.50
4             5                     6          1.000000                         4                 1.00

## Step 14: Convert Education into a Numerical Score
Education is categorical, so we assign simple scores for demonstration.

In [79]:
# This cell maps extracted education values to numerical scores.
# This is only for teaching purposes.

education_map = {
    "B.Com": 0.50,
    "BBA": 0.55,
    "BCA": 0.55,
    "B.Sc": 0.60,
    "B.Tech": 0.70,
    "MBA": 0.75,
    "MBA HR": 0.80,
    "MCA": 0.80,
    "M.Sc": 0.80,
    "M.Tech": 0.90,
    "M.Stat": 0.90
}

df["education_score"] = df["education_extracted"].map(education_map)

df[["candidate_id", "education_extracted", "education_score"]].head(10)

   candidate_id     education_extracted  education_score
0             1  B.Tech. Certifications              NaN
1             2  MBA HR. Certifications              NaN
2             3    B.Sc. Certifications              NaN
3             4  B.Tech. Certifications              NaN
4             5  M.Tech. Certifications              NaN
5             6  MBA HR. Certifications              NaN
6             7  B.Tech. Certifications              NaN
7             8    M.Sc. Certifications              NaN
8             9     BCA. Certifications              NaN
9            10     MCA. Certifications              NaN

## Step 15: Create Final Resume Matching Score
Now we combine:
- keyword matching
- text similarity
- experience
- education
- certifications

This gives a final candidate relevance score.

In [80]:
# This cell creates a final weighted score.
# We first normalize the keyword match count.
# Then we combine all scores using weights.

df["keyword_score"] = df["keyword_match_count"] / len(required_keywords)

df["final_score"] = (
    0.30 * df["keyword_score"] +
    0.30 * df["similarity_score"] +
    0.20 * df["experience_score"] +
    0.10 * df["education_score"] +
    0.10 * df["certification_score"]
)

df[[
    "candidate_id",
    "keyword_score",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score"
]].head(10)

   candidate_id  keyword_score  similarity_score  experience_score  education_score  certification_score  final_score
0             1          0.375          0.432462          0.500000              NaN                 0.50          NaN
1             2          0.250          0.232806          0.666667              NaN                 0.25          NaN
2             3          0.250          0.107773          0.333333              NaN                 0.75          NaN
3             4          0.250          0.122363          0.833333              NaN                 0.50          NaN
4             5          0.375          0.354681          1.000000              NaN                 1.00          NaN
5             6          0.250          0.179471          0.500000              NaN                 0.50          NaN
6             7          0.375          0.442718          0.666667              NaN                 0.50          NaN
7             8          0.250          0.261416          0.333333              NaN                 0.75          NaN
8             9          0.125          0.059033          0.833333              NaN                 0.25          NaN
9            10          0.500          0.331545          0.500000              NaN                 0.75          NaN

## Step 16: Rank Candidates
Now we sort candidates from highest final score to lowest final score.

In [81]:
# This cell ranks candidates based on final score.

ranked_df = df.sort_values(by="final_score", ascending=False).reset_index(drop=True)

ranked_df[[
    "candidate_id",
    "skills_extracted",
    "experience_extracted",
    "education_extracted",
    "certifications_extracted",
    "final_score"
]]

    candidate_id                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  final_score
0              1           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2          NaN
1              2  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1          NaN
2              3    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3          NaN
3              4     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2          NaN
4              5          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4          NaN
5              6  Recruitment, Sourcing, Interview Screening, an...                     3  MBA HR. Certifications                         2          NaN
6              7       Python, SQL, Power BI, Excel, and Statistics                     4  B.Tech. Certifications                         2          NaN
7              8  Machine Learning, Python, Tableau, and Data Vi...                     2    M.Sc. Certifications                         3          NaN
8              9  Manual Testing, Selenium, Jira, and Communication                     5     BCA. Certifications                         1          NaN
9             10  Python, SQL, NLP, ML, Communication, and Teamwork                     3     MCA. Certifications                         3          NaN
10            11  Excel, SQL, Dashboarding, Reporting, and Power BI                     2   B.Com. Certifications                         2          NaN
11            12        Python, R, Statistics, and Machine Learning                     4  M.Stat. Certifications                         3          NaN
12            13  Project Management, Agile, Scrum, and Communic...                     6     MBA. Certifications                         2          NaN
13            14  Python, SQL, Data Analysis, Recruitment, and H...                     5  MBA HR. Certifications                         4          NaN
14            15  C++, Algorithms, Data Structures, and Problem ...                     0  B.Tech. Certifications                         1          NaN
15            16  Python, SQL, Tableau, Power BI, and Communication                     3     BBA. Certifications                         2          NaN
16            17  NLP, BERT, Transformers, Python, and Machine L...                     5  M.Tech. Certifications                         4          NaN
17            18  Recruitment Analytics, Excel, Communication, a...                     4  MBA HR. Certifications                         2          NaN
18            19  Python, SQL, Statistics, Data Cleaning, and Pa...                     2    B.Sc. Certifications                         2          NaN
19            20  Python, Machine Learning, SQL, Communication, ...                     4     MCA. Certifications                         3          NaN

## Step 17: Identify Top 5 Best-Fit Candidates
These are the strongest candidates according to the ATS-style AI screening logic.

In [82]:
# This cell extracts the top 5 candidates.

top_5 = ranked_df.head(5)

top_5[[
    "candidate_id",
    "skills_extracted",
    "experience_extracted",
    "education_extracted",
    "certifications_extracted",
    "final_score"
]]

   candidate_id                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  final_score
0             1           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2          NaN
1             2  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1          NaN
2             3    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3          NaN
3             4     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2          NaN
4             5          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4          NaN

## Step 18: Add Recommendation Labels
This makes the output more interpretable for HR.

In [83]:
# This cell converts numeric final scores into recommendation labels.

def label_candidate(score):
    if score >= 0.65:
        return "Strong Fit"
    elif score >= 0.50:
        return "Moderate Fit"
    else:
        return "Low Fit"

ranked_df["recommendation"] = ranked_df["final_score"].apply(label_candidate)

ranked_df[[
    "candidate_id",
    "final_score",
    "recommendation"
]]

    candidate_id  final_score recommendation
0              1          NaN        Low Fit
1              2          NaN        Low Fit
2              3          NaN        Low Fit
3              4          NaN        Low Fit
4              5          NaN        Low Fit
5              6          NaN        Low Fit
6              7          NaN        Low Fit
7              8          NaN        Low Fit
8              9          NaN        Low Fit
9             10          NaN        Low Fit
10            11          NaN        Low Fit
11            12          NaN        Low Fit
12            13          NaN        Low Fit
13            14          NaN        Low Fit
14            15          NaN        Low Fit
15            16          NaN        Low Fit
16            17          NaN        Low Fit
17            18          NaN        Low Fit
18            19          NaN        Low Fit
19            20          NaN        Low Fit

## Step 19: Final Structured Resume Screening Output
This output represents the parsed and ranked candidate dataset.

In [84]:
# This cell creates the final output table.

final_output = ranked_df[[
    "candidate_id",
    "resume_text",
    "skills_extracted",
    "experience_extracted",
    "education_extracted",
    "certifications_extracted",
    "keyword_match_count",
    "keyword_score",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score",
    "recommendation"
]]

final_output

    candidate_id                                        resume_text                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  keyword_match_count  keyword_score  similarity_score  experience_score  education_score  certification_score  final_score recommendation
0              1  Aarav has skills in Python, SQL, Excel, and Ma...           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2                    3          0.375          0.432462          0.500000              NaN                 0.50          NaN        Low Fit
1              2  Diya has skills in Recruitment, Onboarding, Co...  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1                    2          0.250          0.232806          0.666667              NaN                 0.25          NaN        Low Fit
2              3  Kabir has skills in Python, SQL, Tableau, Data...    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3                    2          0.250          0.107773          0.333333              NaN                 0.75          NaN        Low Fit
3              4  Ishita has skills in Java, SQL, Spring, Teamwo...     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2                    2          0.250          0.122363          0.833333              NaN                 0.50          NaN        Low Fit
4              5  Vivaan has skills in Python, SQL, Deep Learnin...          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4                    3          0.375          0.354681          1.000000              NaN                 1.00          NaN        Low Fit
5              6  Anaya has skills in Recruitment, Sourcing, Int...  Recruitment, Sourcing, Interview Screening, an...                     3  MBA HR. Certifications                         2                    2          0.250          0.179471          0.500000              NaN                 0.50          NaN        Low Fit
6              7  Reyansh has skills in Python, SQL, Power BI, E...       Python, SQL, Power BI, Excel, and Statistics                     4  B.Tech. Certifications                         2                    3          0.375          0.442718          0.666667              NaN                 0.50          NaN        Low Fit
7              8  Myra has skills in Machine Learning, Python, T...  Machine Learning, Python, Tableau, and Data Vi...                     2    M.Sc. Certifications                         3                    2          0.250          0.261416          0.333333              NaN                 0.75          NaN        Low Fit
8              9  Arjun has skills in Manual Testing, Selenium, ...  Manual Testing, Selenium, Jira, and Communication                     5     BCA. Certifications                         1                    1          0.125          0.059033          0.833333              NaN                 0.25          NaN        Low Fit
9             10  Siya has skills in Python, SQL, NLP, ML, Commu...  Python, SQL, NLP, ML, Communication, and Teamwork                     3     MCA. Certifications                         3                    4          0.500          0.331545          0.500000              NaN                 0.75          NaN        Low Fit
10            11  Krish has skills in Excel, SQL, Dashboarding, ...  Excel, SQL, Dashboarding, Reporting, and Power BI                     2   B.Com. Certifications                         2                    2          0.250          0.321523          0.333333              NaN                 0.50          NaN        Low Fit
11            12  Aadhya has skills in Python, R, Statistics, an...        Python, R, Statistics, and Machine Learning                     4  M.Stat. Certifications                         3                    2          0.250          0.358262          0.666667              NaN                 0.75          NaN        Low Fit
12            13  Advik has skills in Project Management, Agile,...  Project Management, Agile, Scrum, and Communic...                     6     MBA. Certifications                         2                    1          0.125          0.059033          1.000000              NaN                 0.50          NaN        Low Fit
13            14  Kiara has skills in Python, SQL, Data Analysis...  Python, SQL, Data Analysis, Recruitment, and H...                     5  MBA HR. Certifications                         4                    4          0.500          0.386489          0.833333              NaN                 1.00          NaN        Low Fit
14            15  Atharv has skills in C++, Algorithms, Data Str...  C++, Algorithms, Data Structures, and Problem ...                     0  B.Tech. Certifications                         1                    0          0.000          0.000000          0.000000              NaN                 0.25          NaN        Low Fit
15            16  Navya has skills in Python, SQL, Tableau, Powe...  Python, SQL, Tableau, Power BI, and Communication                     3     BBA. Certifications                         2                    4          0.500          0.540387          0.500000              NaN                 0.50          NaN        Low Fit
16            17  Rudra has skills in NLP, BERT, Transformers, P...  NLP, BERT, Transformers, Python, and Machine L...                     5  M.Tech. Certifications                         4                    3          0.375          0.397459          0.833333              NaN                 1.00          NaN        Low Fit
17            18  Sara has skills in Recruitment Analytics, Exce...  Recruitment Analytics, Excel, Communication, a...                     4  MBA HR. Certifications                         2                    3          0.375          0.346614          0.666667              NaN                 0.50          NaN        Low Fit
18            19  Vihaan has skills in Python, SQL, Statistics, ...  Python, SQL, Statistics, Data Cleaning, and Pa...                     2    B.Sc. Certifications                         2                    2          0.250          0.104096          0.333333              NaN                 0.50          NaN        Low Fit
19            20  Meera has skills in Python, Machine Learning, ...  Python, Machine Learning, SQL, Communication, ...                     4     MCA. Certifications                         3                    4          0.500          0.435013          0.666667              NaN                 0.75          NaN        Low Fit

## Step 20: Save the Final Output as CSV
This allows the result to be used later in Excel, Power BI, or reports.

In [85]:
# This cell saves the final output as a CSV file.

final_output.to_csv("resume_parsing_screening_output.csv", index=False)

print("File saved successfully as resume_parsing_screening_output.csv")

File saved successfully as resume_parsing_screening_output.csv

## Step 21: Conclusion

In this lab, we learned how to:
- create synthetic resume data
- treat resume text as unstructured input
- extract skills, experience, education, and certifications
- simulate ATS-style keyword filtering
- apply TF-IDF and cosine similarity
- rank candidates based on relevance
- identify best-fit candidates

## Final Insight
This lab shows how AI supports resume parsing and screening.
However, final hiring decisions should still involve HR professionals because:
- keyword systems may miss context
- parsing may make extraction errors
- fairness and human judgment remain essential

In [86]:
# ============================================================
# LAST CELL: SAVE FINAL OUTPUT AS CSV AND DOWNLOAD IT
# ============================================================

# Save DataFrame as CSV file
final_output.to_csv("resume_parsing_screening_output.csv", index=False)

print("CSV file created successfully.")

# Import Colab files module
from google.colab import files

# Automatically download file to your computer
files.download("resume_parsing_screening_output.csv")

CSV file created successfully.